# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import kratos_pb2 as kratos__pb2


class KratosServiceStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Status = channel.unary_unary(
        '/kratos.KratosService/Status',
        request_serializer=kratos__pb2.StatusRequest.SerializeToString,
        response_deserializer=kratos__pb2.StatusResponse.FromString,
        )
    self.AddRule = channel.unary_unary(
        '/kratos.KratosService/AddRule',
        request_serializer=kratos__pb2.AddRuleRequest.SerializeToString,
        response_deserializer=kratos__pb2.AddRuleResponse.FromString,
        )
    self.DeleteRule = channel.unary_unary(
        '/kratos.KratosService/DeleteRule',
        request_serializer=kratos__pb2.DeleteRuleRequest.SerializeToString,
        response_deserializer=kratos__pb2.DeleteRuleResponse.FromString,
        )
    self.ResetCounter = channel.unary_unary(
        '/kratos.KratosService/ResetCounter',
        request_serializer=kratos__pb2.ResetCounterRequest.SerializeToString,
        response_deserializer=kratos__pb2.ResetCounterResponse.FromString,
        )
    self.AddService = channel.unary_unary(
        '/kratos.KratosService/AddService',
        request_serializer=kratos__pb2.AddServiceRequest.SerializeToString,
        response_deserializer=kratos__pb2.AddServiceResponse.FromString,
        )
    self.DeleteService = channel.unary_unary(
        '/kratos.KratosService/DeleteService',
        request_serializer=kratos__pb2.DeleteServiceRequest.SerializeToString,
        response_deserializer=kratos__pb2.DeleteServiceResponse.FromString,
        )


class KratosServiceServicer(object):

  def Status(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddRule(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteRule(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ResetCounter(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddService(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteService(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_KratosServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Status': grpc.unary_unary_rpc_method_handler(
          servicer.Status,
          request_deserializer=kratos__pb2.StatusRequest.FromString,
          response_serializer=kratos__pb2.StatusResponse.SerializeToString,
      ),
      'AddRule': grpc.unary_unary_rpc_method_handler(
          servicer.AddRule,
          request_deserializer=kratos__pb2.AddRuleRequest.FromString,
          response_serializer=kratos__pb2.AddRuleResponse.SerializeToString,
      ),
      'DeleteRule': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteRule,
          request_deserializer=kratos__pb2.DeleteRuleRequest.FromString,
          response_serializer=kratos__pb2.DeleteRuleResponse.SerializeToString,
      ),
      'ResetCounter': grpc.unary_unary_rpc_method_handler(
          servicer.ResetCounter,
          request_deserializer=kratos__pb2.ResetCounterRequest.FromString,
          response_serializer=kratos__pb2.ResetCounterResponse.SerializeToString,
      ),
      'AddService': grpc.unary_unary_rpc_method_handler(
          servicer.AddService,
          request_deserializer=kratos__pb2.AddServiceRequest.FromString,
          response_serializer=kratos__pb2.AddServiceResponse.SerializeToString,
      ),
      'DeleteService': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteService,
          request_deserializer=kratos__pb2.DeleteServiceRequest.FromString,
          response_serializer=kratos__pb2.DeleteServiceResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'kratos.KratosService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
